CREATE DATABASE IF NOT EXISTS `movieRental`
    DEFAULT CHARACTER SET utf8
    DEFAULT COLLATE utf8_general_ci;

CREATE TABLE IF NOT EXISTS `movieRental`.`movies`(
    `id` CHAR (36) NOT NULL,
    `title` VARCHAR (80) NOT NULL UNIQUE,
    `director` VARCHAR (80) NOT NULL,
    `quantities` INT UNSIGNED NOT NULL,
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`title`) 
) ENGINE = InnoDB;


CREATE TABLE IF NOT EXISTS `movieRental`.`users`(
    `id` CHAR(36) NOT NULL, 
    `name` VARCHAR(80) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `role` ENUM('user', 'admin', 'disabled') DEFAULT 'user',
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    PRIMARY KEY(`id`)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `movieRental`.`rentals`(
    `id` CHAR(36) NOT NULL,
    `titleMovie` VARCHAR(80) NOT NULL,
    `idUser` CHAR(36) NOT NULL,
    `status` ENUM('RENTED','RETURNED') DEFAULT 'RENTED',
    `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updateAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY(`id`),
    FOREIGN KEY (`idUser`) REFERENCES `users`(`id`),
    FOREIGN KEY (`titleMovie`) REFERENCES `movies`(`title`)
) ENGINE = InnoDB;